iface: enp8s0
fname: ""
snaplen: 1600
filter: tcp and port 80
nickname:
    - YumeMichi
super_users:
    - "785569962"
    - "1157490807"
admin_user: "1157490807"
cqhttp_host: 127.0.0.1
cqhttp_port: "6700"
access_token: "klab"
redis_host: 127.0.0.1
redis_port: "6379"
redis_password: ""
redis_db: 0
mysql_host: 127.0.0.1
mysql_port: "3306"
mysql_user: "root"
mysql_password: "sifrank"
mysql_db: "sifrank"
groups:
    - "728481207"
    - "794573579"
app_name: LoveLive! 国服档线小助手
event_name: "亲密接触运动会"
end_time: "2021-08-09 14:00:00"
icon_url: https://c-ssl.duitang.com/uploads/item/201906/07/20190607235250_wtjcy.thumb.1000_0.jpg
