iface: enp8s0
fname: ""
snaplen: 1600
filter: tcp and port 80
nickname:
    - YumeMichi
super_users:
    - 785569962
    - 1157490807
admin_user: "1157490807"
cqhttp_host: 127.0.0.1
cqhttp_port: "6700"
access_token: "klab"
redis_host: 127.0.0.1
redis_port: "6379"
redis_password: "xcwl@501"
redis_db: 0
mysql_host: 127.0.0.1
mysql_port: "3306"
mysql_user: "root"
mysql_password: "123456"
mysql_db: "sifrank"
leveldb_path: "/data/leveldb/sifrank.db"
app_name: LoveLive! 国服档线小助手
event_name: "μ's 的文化节"
start_time: "2022-04-14 15:00:00"
end_time: "2022-04-24 14:00:00"
dq_x_offset: 62
dq_x_step: 160
dq_x_extra: 14
dq_y_offset: 178
dq_y_step: 46
dq_title: "国服 第38次 Challenge Festival 《μ's 的文化节》\t果/凛绘\t04.14-04.24"
dq_subtitle: ""
dq_font_name: "./assets/fonts/simsun.ttc"
dq_font_size: 32
dq_title_x_offset: 400
dq_title_y_offset: 60
dq_subtitle_x_offset: 1800
dq_subtitle_y_offset: 60
dq_base_image: "./assets/images/base.jpg"
dq_output_dir: "./temp"
