iface: enp8s0
fname: ""
snaplen: 1600
filter: tcp and port 80
nickname:
    - YumeMichi
super_users:
    - "785569962"
    - "1157490807"
cqhttp_host: 127.0.0.1
cqhttp_port: "6700"
access_token: ""
redis_host: 127.0.0.1
redis_port: "6379"
redis_password: ""
redis_db: 0
groups:
    - "794573579"
    - "728481207"
