iface: enp8s0
fname: ""
snaplen: 1600
filter: tcp and port 80
nickname:
    - YumeMichi
super_users:
    - "785569962"
    - "1157490807"
admin_user: "1157490807"
cqhttp_host: 127.0.0.1
cqhttp_port: "6700"
access_token: ""
redis_host: 127.0.0.1
redis_port: "6379"
redis_password: ""
redis_db: 0
groups:
    - "728481207"
    - "794573579"
app_name: LoveLive! 国服档线小助手
event_name: "Guilty Kiss 的作风!"
end_time: "2021-04-06 14:00:00"
icon_url: https://c-ssl.duitang.com/uploads/item/201906/07/20190607235250_wtjcy.thumb.1000_0.jpg
