app_name: LoveLive! 国服档线小助手
log:
    log_dir: logs
    log_level: 5
    log_save: true
pcap:
    iface: enp8s0
    fname: ""
    snaplen: 1600
    filter: tcp and port 80
bot:
    nickname:
        - YumeMichi
    super_users:
        - 785569962
        - 1157490807
    admin_user: 1157490807
    cqhttp_host: 127.0.0.1
    cqhttp_port: 6700
    access_token: klab
leveldb:
    data_path: /data/leveldb/sifrank.db
event:
    event_name: 红叶之秋 Aqours之秋
    start_time: "2022-07-01 15:00:00"
    end_time: "2022-07-11 14:00:00"
