iface: enp8s0
fname: ""
snaplen: 1600
filter: tcp and port 80
nickname:
    - YumeMichi
super_users:
    - "785569962"
    - "1157490807"
admin_user: "1157490807"
cqhttp_host: 127.0.0.1
cqhttp_port: "6700"
access_token: "klab"
redis_host: 127.0.0.1
redis_port: "6379"
redis_password: "xcwl@501"
redis_db: 0
mysql_host: 127.0.0.1
mysql_port: "3306"
mysql_user: "root"
mysql_password: "123456"
mysql_db: "sifrank"
groups:
    - "728481207"
    - "794573579"
    - "580235177"
app_name: LoveLive! 国服档线小助手
event_name: "暑假不要结束"
start_time: "2022-03-28 15:00:00"
end_time: "2022-04-08 14:00:00"
dq_x_offset: 62
dq_x_step: 160
dq_x_extra: 15
dq_y_offset: 178
dq_y_step: 46
dq_title: "国服 第45次 SCORE MATCH 《暑假不要结束》\t善/千鞠\t03.28-04.08"
dq_subtitle: "* 水团双人卡 50% 加成"
dq_font_name: "./assets/fonts/simsun.ttc"
dq_font_size: 32
dq_title_x_offset: 400
dq_title_y_offset: 60
dq_subtitle_x_offset: 1800
dq_subtitle_y_offset: 60
dq_base_image: "./assets/images/base.jpg"
dq_output_dir: "./temp"
